### PR TITLE
Support for CP-SCP Wrapper

### PR DESCRIPTION
**Pull request by Hexer10**

### CODE REVIEW

**Comment by shanapu** [comment]
Nice thing!
please also add the this snipped to playertags.sp and add cp-scp-wrapper.inc to the PR.
Thank you very much!

**Comment by Hexer10** [comment]
Uh, sure that I will.

**Comment by Hexer10** [comment]
Also thanks to all who helped me in the AM Thread: https://forums.alliedmods.net/showthread.php?t=300934

**Comment by shanapu** [comment]
Thanks for all your great work and help on MyJailbreak!

**Pull request merged**
